/**
 * Toshkentdagi haqiqiy ish joylari — OSM koordinatalar + haqiqiy rasmlar
 */
const REAL_PLACES = [
  {
    id: 1,
    name: "O'zbekiston Milliy kutubxonasi (Alisher Navoi)",
    type: "library",
    address: "Navoiy ko'chasi, 1",
    district: "Yunusobod",
    latitude: "41.317076",
    longitude: "69.274454",
    price: "0",
    wifi_speed: 50,
    noise_level: "quiet",
    sockets: true,
    capacity: 200,
    available_seats: 85,
    rating: "4.60",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/National_library_of_Uzbekistan_%28Milliy_kutubxona%29.jpg/800px-National_library_of_Uzbekistan_%28Milliy_kutubxona%29.jpg",
    description: "O'zbekistonning eng yirik kutubxonasi. Tinch o'qish va ish zonalari, bepul Wi-Fi. Talabalar va tadqiqotchilar uchun ideal joy.",
    working_hours: { "dush-juma": "09:00-20:00", "shanba": "09:00-17:00" },
    amenities: ["Wi-Fi", "Bepul", "Jim joy", "Rozetka", "Konditsioner"],
    is_real: true,
  },
  {
    id: 2,
    name: "[hub] module Coworking",
    type: "coworking",
    address: "Tarasa Shevchenko ko'chasi, 42",
    district: "Mirzo Ulug'bek",
    latitude: "41.295605",
    longitude: "69.282037",
    price: "130000",
    wifi_speed: 100,
    noise_level: "moderate",
    sockets: true,
    capacity: 30,
    available_seats: 12,
    rating: "4.80",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
    description: "Toshkent markazidagi zamonaviy kоворking. Open space, meeting room, zoom room va tez internet.",
    working_hours: { "dush-yak": "09:00-21:00" },
    amenities: ["Wi-Fi", "Meeting room", "Zoom room", "Oshxona", "Parking"],
    is_real: true,
  },
  {
    id: 3,
    name: "BookCafe",
    type: "cafe",
    address: "Istiqbol ko'chasi, 8",
    district: "Mirabad",
    latitude: "41.307804",
    longitude: "69.282473",
    price: "35000",
    wifi_speed: 70,
    noise_level: "quiet",
    sockets: true,
    capacity: 45,
    available_seats: 18,
    rating: "4.70",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    description: "Kutubxona muhitidagi kafe. Laptop bilan ishlash uchun qulay, tinch va ilmiy muhit.",
    working_hours: { "dush-yak": "08:00-22:00" },
    amenities: ["Wi-Fi", "Kofe", "Rozetka", "Kitoblar", "Tinch"],
    is_real: true,
  },
  {
    id: 4,
    name: "IT Park Tashkent",
    type: "coworking",
    address: "Mahtumquli ko'chasi, 114a",
    district: "Yashnobod",
    latitude: "41.302761",
    longitude: "69.314783",
    price: "80000",
    wifi_speed: 150,
    noise_level: "moderate",
    sockets: true,
    capacity: 80,
    available_seats: 25,
    rating: "4.75",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80",
    description: "IT ekotizim markazi. Startaplar va dasturchilar uchun yuqori tezlikdagi internet va zamonaviy infratuzilma.",
    working_hours: { "dush-juma": "09:00-18:00" },
    amenities: ["Wi-Fi", "Meeting room", "Printer", "IT community", "Parking"],
    is_real: true,
  },
  {
    id: 5,
    name: "Tashkent City Mall",
    type: "free_zone",
    address: "Botir Zokirov ko'chasi, 7",
    district: "Shayxontohur",
    latitude: "41.316264",
    longitude: "69.252413",
    price: "0",
    wifi_speed: 40,
    noise_level: "moderate",
    sockets: true,
    capacity: 150,
    available_seats: 60,
    rating: "4.30",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    description: "Savdo markazi ichida bepul Wi-Fi zonalar. Food court yonida laptop bilan ishlash mumkin.",
    working_hours: { "dush-yak": "10:00-23:00" },
    amenities: ["Wi-Fi", "Bepul", "Kafe", "Konditsioner", "Parking"],
    is_real: true,
  },
  {
    id: 6,
    name: "C-Space Labzak",
    type: "coworking",
    address: "Labzak ko'chasi, 64A",
    district: "Shayxontohur",
    latitude: "41.327168",
    longitude: "69.259727",
    price: "60000",
    wifi_speed: 100,
    noise_level: "quiet",
    sockets: true,
    capacity: 50,
    available_seats: 20,
    rating: "5.00",
    image: "https://images.unsplash.com/photo-1497215847834-39b7ad046d7f?w=800&q=80",
    description: "24/7 ochiq kоворking markaz. Barqaror internet, qulay o'rindiqlar va do'stona jamoa.",
    working_hours: { "dush-yak": "24 soat" },
    amenities: ["Wi-Fi", "24/7", "Rozetka", "Community", "Tinch"],
    is_real: true,
  },
  {
    id: 7,
    name: "Union Café",
    type: "cafe",
    address: "Labzak ko'chasi",
    district: "Shayxontohur",
    latitude: "41.332201",
    longitude: "69.263845",
    price: "30000",
    wifi_speed: 60,
    noise_level: "moderate",
    sockets: true,
    capacity: 35,
    available_seats: 14,
    rating: "4.50",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    description: "Laptop friendly kafe. Tez Wi-Fi, rozetkalar va qulay o'rindiqlar.",
    working_hours: { "dush-yak": "08:00-23:00" },
    amenities: ["Wi-Fi", "Kofe", "Rozetka", "Desert"],
    is_real: true,
  },
  {
    id: 8,
    name: "Bon! Cafe",
    type: "cafe",
    address: "Ukchi ko'chasi, 5 (Tashkent City)",
    district: "Shayxontohur",
    latitude: "41.316565",
    longitude: "69.245236",
    price: "40000",
    wifi_speed: 65,
    noise_level: "moderate",
    sockets: true,
    capacity: 40,
    available_seats: 16,
    rating: "4.55",
    image: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    description: "Tashkent City biznes markazidagi mashhur kafe. Ish uchun qulay stollar va yaxshi kofe.",
    working_hours: { "dush-yak": "08:00-00:00" },
    amenities: ["Wi-Fi", "Kofe", "Rozetka", "Markaziy joy"],
    is_real: true,
  },
  {
    id: 9,
    name: "Costa Coffee (Gandhi)",
    type: "cafe",
    address: "Mahatma Gandhi ko'chasi, 14",
    district: "Mirzo Ulug'bek",
    latitude: "41.314009",
    longitude: "69.293918",
    price: "35000",
    wifi_speed: 55,
    noise_level: "moderate",
    sockets: true,
    capacity: 30,
    available_seats: 10,
    rating: "4.40",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    description: "Xalqaro kafe tarmog'i. Barqaror Wi-Fi va qulay muhit.",
    working_hours: { "dush-yak": "08:00-23:00" },
    amenities: ["Wi-Fi", "Kofe", "Rozetka", "Konditsioner"],
    is_real: true,
  },
  {
    id: 10,
    name: "Costa Coffee (Istiqbol)",
    type: "cafe",
    address: "Istiqbol ko'chasi",
    district: "Yashnobod",
    latitude: "41.307502",
    longitude: "69.283978",
    price: "35000",
    wifi_speed: 55,
    noise_level: "moderate",
    sockets: true,
    capacity: 28,
    available_seats: 11,
    rating: "4.35",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    description: "Istiqbol ko'chasidagi Costa Coffee filiali. Laptop bilan ishlash uchun mos.",
    working_hours: { "dush-yak": "08:00-23:00" },
    amenities: ["Wi-Fi", "Kofe", "Rozetka"],
    is_real: true,
  },
  {
    id: 11,
    name: "Space Coworking",
    type: "coworking",
    address: "Gulnor Bashirova ko'chasi",
    district: "Mirzo Ulug'bek",
    latitude: "41.330065",
    longitude: "69.332784",
    price: "70000",
    wifi_speed: 90,
    noise_level: "quiet",
    sockets: true,
    capacity: 25,
    available_seats: 9,
    rating: "4.65",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    description: "Mirzo Ulug'bek tumanidagi kоворking markaz. Tinch muhit va tez internet.",
    working_hours: { "dush-juma": "09:00-20:00" },
    amenities: ["Wi-Fi", "Meeting room", "Tinch", "Printer"],
    is_real: true,
  },
  {
    id: 12,
    name: "Coworking Center (Chilanzar)",
    type: "coworking",
    address: "Chilanzar ko'chasi",
    district: "Chilonzor",
    latitude: "41.279290",
    longitude: "69.217826",
    price: "50000",
    wifi_speed: 80,
    noise_level: "quiet",
    sockets: true,
    capacity: 20,
    available_seats: 8,
    rating: "4.45",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    description: "Chilanzar tumanidagi kоворking markaz. Arzon narx va qulay sharoit.",
    working_hours: { "dush-juma": "09:00-19:00" },
    amenities: ["Wi-Fi", "Rozetka", "Tinch", "Arzon"],
    is_real: true,
  },
];
